//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace EventManagerPro.Model
{
    public partial class BudgetItem
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Cost { get; set; }
        public int BudgetId { get; set; }
    }
    
}
