//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace EventManagerPro.Model
{
    public partial class Event
    {
        public Event()
        {
            this.Guests = new HashSet<Student>();
            this.SubEvents = new HashSet<SubEvent>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime TimeCreated { get; set; }
        public string StudentMatricId { get; set; }
        public int VenueId { get; set; }
        public short ViewAtLoginPage { get; set; }
        public System.DateTime Start { get; set; }
        public System.DateTime End { get; set; }
    
        public virtual Student Owner { get; set; }
        public virtual ICollection<Student> Guests { get; set; }
        public virtual Budget Budget { get; set; }
        public virtual ICollection<SubEvent> SubEvents { get; set; }
    }
    
}
