//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace EventManagerPro.Model
{
    public partial class Student
    {
        public Student()
        {
            this.OwnedEvents = new HashSet<Event>();
            this.RegisteredEvents = new HashSet<Event>();
        }
    
        public string Name { get; set; }
        public string MatricId { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Event> OwnedEvents { get; set; }
        public virtual ICollection<Event> RegisteredEvents { get; set; }
    }
    
}
