//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace EventManagerPro.Model
{
    public partial class SubEvent
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Start { get; set; }
        public string End { get; set; }
        public int EventId { get; set; }
        public int VenueId { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Venue Venue { get; set; }
    }
    
}
